
service: fci-integracion-produccion

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  # iam:
  #   Role:
  cors:
    origins: "*"
    headers:
      - Content-Type
    allowCredentials: true
  iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronConfiguracionTable
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronValoresTable
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronUsersTable
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronReportesTable
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronAlertasTable
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/CamaronPiscinasTable


functions:
  hello:
    handler: src/handler.hello

# Api de Camaron
  CamaronGetBoxConfig:
    handler: src/camaron/getBoxConfig.getBoxConfig
    events:
      - httpApi:
          path: /camaronGetBoxConfig
          method: get

  CamaronSetBoxConfig:
    handler: src/camaron/setBoxConfig.setBoxConfig
    events:
      - httpApi:
          path: /camaronSetBoxConfig
          method: post



  CamaronAddValores:
    handler: src/camaron/addValores.addValores
    events:
      - httpApi:
          path: /camaronAddValores
          method: post

  CamaronGetValores:
    handler: src/camaron/getValores.getValores
    events:
      - httpApi:
          path: /camaronGetValores
          method: post

  CamaronGetAllValores:
    handler: src/camaron/getAllValores.getAllValores
    events:
      - httpApi:
          path: /camaronGetAllValores
          method: get



  CamaronGetUsers:
    handler: src/camaron/getUsers.getUsers
    events:
      - httpApi:
          path: /camaronGetUsers
          method: get

  CamaronAddUser:
    handler: src/camaron/addUser.addUser
    events:
      - httpApi:
          path: /camaronAddUser
          method: post



  CamaronGetReportes:
    handler: src/camaron/getReportes.getReportes
    events:
      - httpApi:
          path: /camaronGetReportes
          method: get

  CamaronAddReporte:
    handler: src/camaron/addReporte.addReporte
    events:
      - httpApi:
          path: /camaronAddReporte
          method: post



  CamaronAddAlerta:
    handler: src/camaron/addAlerta.addAlerta
    events:
      - httpApi:
          path: /camaronAddAlerta
          method: post

  CamaronGetAlertas:
    handler: src/camaron/getAlertas.getAlertas
    events:
      - httpApi:
          path: /camaronGetAlertas
          method: get



  CamaronGetPiscinas:
    handler: src/camaron/getPiscinas.getPiscinas
    events:
      - httpApi:
          path: /camaronGetPiscinas
          method: get

  CamaronAddPiscinas:
    handler: src/camaron/addPiscina.addPiscina
    events:
      - httpApi:
          path: /CamaronAddPiscina
          method: post
      

  EnviarMail:
    handler: src/camaron/enviarEmail.enviarEmail
    events:
      - httpApi:
          path: /enviarEmail
          method: post
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"


resources:
  Resources:
    CamaronValoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronValoresTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: fecha
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          
    CamaronConfiguracionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronConfiguracionTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    CamaronUsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronUsersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: user
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    CamaronReportesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronReportesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    CamaronAlertasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronAlertasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: fecha
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    CamaronPiscinasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CamaronPiscinasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: fecha
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1